Repository Make-A-Wish-Sopt/Make-A-Wish-Client, pull requests merged in 2023-09, with the labels that each got.

#118 [ style ] 전역스타일링 변경 및 레이아웃으로 구조 변경
  components/common/footer.tsx
  components/common/layout.tsx
  components/login/index.tsx
  components/main/index.tsx
  components/wishes/[id].tsx
  constant/alertMessage.ts
  pages/cakes/[id].tsx
  pages/cakes/approve/index.tsx
  pages/index.tsx
  pages/login/oauth2/code/kakao/index.tsx
  pages/main/index.tsx
  pages/wishes/[id].tsx
  styles/GlobalStyle.tsx
Labels: 홍명헌, Fix, Done

#110 [fix] 링크복사 alert창 오류 수정
  components/common/modal/ShareModal.tsx
Labels: 박재은, Feat, Fix

#111 [fix] QA_이미지 화질 변경(메인, 마이페이지)
  components/common/footer.tsx
  components/common/modal/DeleteModal.tsx
  components/main/cake.tsx
  components/mypage/index.tsx
  components/mypage/links/[id].tsx
  components/mypage/links/index.tsx
  components/mypage/links/noWishLists.tsx
  components/wishes/share/index.tsx
  components/wishes/wishesForm/Preview.tsx
  hooks/queries/letters/useGetCakesCount.ts
  public/assets/images/cakeProfileImg.svg
  public/assets/images/chat/linksPageChatImg.svg
  public/assets/images/chat/mainEndChatImg.svg
  public/assets/images/chat/mainPageChatImg.svg
  public/assets/images/chat/mainWishChatImg.svg
  public/assets/images/chat/sharePageChatImg.svg
  public/assets/images/deleteModalCake.svg
  public/assets/images/index.ts
  public/assets/images/linkBeefCakeImg.png
  public/assets/images/linkPageCake.svg
  public/assets/images/logoImg.svg
  public/assets/images/mainCakeImg.png
  public/assets/images/mainEndCakeImg.png
  public/assets/images/mainEndCakeImg.svg
  public/assets/images/mainLoginImg.png
  public/assets/images/mypageCakeImg.png
  public/assets/images/pillCakeImg.svg
  public/assets/images/wishesChatImg.svg
Labels: 박재은, Fix, UI

#112 Release#106 login page/button fix
  components/login/index.tsx
Labels: 박재은, Fix, UI

#114 [fix] wishes 버튼 텍스트 수정
  components/wishes/[id].tsx
Labels: 박재은, Fix, UI

#120 Release#119 wishes/qa
  components/common/layout.tsx
  components/common/modal/BankInput.tsx
  components/mypage/index.tsx
  components/mypage/letters/[id].tsx
  components/mypage/links/index.tsx
  components/wishes/wishesForm/BankInfo.tsx
  components/wishes/wishesForm/Preview.tsx
  components/wishes/wishesForm/WisehsStep2.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/index.tsx
  constant/siteList.ts
  pages/mypage/editWishes/index.tsx
  pages/mypage/index.tsx
  pages/mypage/letters/[id].tsx
  pages/mypage/letters/[id]/[cakeId].tsx
  pages/mypage/links/[id].tsx
  pages/mypage/links/index.tsx
  pages/wishes/index.tsx
  pages/wishes/share/index.tsx
  styles/GlobalStyle.tsx
  validation/input.ts
Labels: 홍명헌, Fix

#123 Release#115 letters/back btn
  components/common/verticalProgressBar.tsx
  components/main/cake.tsx
  components/mypage/letters/[id].tsx
  components/mypage/links/[id].tsx
Labels: 박재은, Fix, Done

#125 Release#119 wishes/qa
  api/wishes/wishesAPI.ts
  components/common/layout.tsx
  components/common/modal/BankModal.tsx
  components/login/index.tsx
  components/main/index.tsx
  components/wishes/wishesForm/WisehsStep2.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/itemLink.tsx
  next.config.js
  utils/common/extractItem.ts
Labels: 홍명헌, Feat, Fix, UI, Done

#128 Release#127 wishes/share
  components/wishes/[id].tsx
  components/wishes/share/index.tsx
  hooks/queries/login/useAuthKakao.ts
Labels: 박재은, Fix, Done

#131 Release#126 common/style
  api/cakes/cakesAPI.ts
  api/common/axios.ts
  api/wishes/wishesAPI.ts
  components/cakes/index.tsx
  components/common/input/inputBox.tsx
  components/common/input/inputContainer.tsx
  components/common/layout.tsx
  components/common/modal/CustomDatePicker.tsx
  components/login/index.tsx
  components/main/cake.tsx
  components/mypage/EditWishes/index.tsx
  components/mypage/index.tsx
  components/mypage/letters/[id].tsx
  components/wishes/[id].tsx
  components/wishes/share/index.tsx
  components/wishes/wishesForm/BankInfo.tsx
  components/wishes/wishesForm/Preview.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/itemLink.tsx
  hooks/queries/cakes/useRequestPayReady.ts
  hooks/queries/mypage/useEditWishesInfo.tsx
  hooks/queries/wishes/useCreateWishesLink.ts
  hooks/wishes/useUploadItemInfo.ts
  pages/cakes/approve/index.tsx
  pages/wishes/[id].tsx
  styles/GlobalStyle.tsx
  styles/theme.ts
  utils/common/extractItem.ts
  utils/common/getDate.ts
Labels: 홍명헌, Fix, Done

#133 Release#132 common/style
  api/mypage/mypageAPI.ts
  components/common/box/BasicBox.tsx
  components/common/footer.tsx
  components/common/input/inputBox.tsx
  components/common/input/textareaBox.tsx
  components/login/index.tsx
  components/mypage/EditWishes/index.tsx
  components/wishes/wishesForm/Preview.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/itemImageBox.tsx
  components/wishes/wishesForm/itemLink.tsx
  styles/GlobalStyle.tsx
  styles/theme.ts
Labels: 홍명헌, UI

#140 [ feat ] GA 커스텀 코드 적용
  pages/_app.tsx
Labels: 홍명헌, Feat
