Repository Make-A-Wish-Sopt/Make-A-Wish-Client, pull requests merged in 2023-08, with the labels that each got.

#66 Feat64 editwishes
  api/common/path.ts
  api/mypage/getUserInfo.ts
  api/wishes/createWishesLink.ts
  api/wishes/editUserAccount.ts
  api/wishes/editWishesInfo.ts
  api/wishes/getUserAccount.ts
  components/Mypage/EditWishes/index.tsx
  components/common/modal/BankInput.tsx
  components/wishes/wishesForm/BankInfo.tsx
  components/wishes/wishesForm/Preview.tsx
  components/wishes/wishesForm/WisehsStep2.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/index.tsx
  components/wishes/wishesForm/itemLink.tsx
  constant/queryKey.ts
  hooks/common/useUserInfo.tsx
  hooks/queries/wishes/useCreateWishesLink.ts
  hooks/queries/wishes/useGetUserAccount.tsx
  hooks/wishes/useWisehsStep.tsx
  pages/cakes/[id].tsx
  pages/mypage/editWishes/index.tsx
  recoil/formPage/wishesData.ts
  types/mypage/userInfoType.ts
  types/queryKeyType.ts
  types/wishes/accountInfotype.ts
  types/wishes/wishesDataType.ts
Labels: 홍명헌, Feat, Done

#74 Feat#73 mypage
  api/letters/getCakeLetters.ts
  api/letters/getCakesCount.ts
  api/links/deleteWishLinks.ts
  api/links/getOneWish.ts
  api/links/getWishLinks.ts
  api/login/sendCodeToServer.ts
  components/common/modal/DeleteModal.tsx
  components/common/modal/GuideModal.tsx
  components/mypage/index.tsx
  components/mypage/itemBox.tsx
  components/mypage/letters/[id].tsx
  components/mypage/letters/cakeListButton.tsx
  components/mypage/letters/cakeListText.tsx
  components/mypage/letters/index.tsx
  components/mypage/letters/lettersMain.tsx
  components/mypage/links/[id].tsx
  components/mypage/links/index.tsx
  components/mypage/links/linksBox.tsx
  components/mypage/links/noWishLists.tsx
  components/mypage/links/wishLists.tsx
  constant/queryKey.ts
  constant/snsList.ts
  hooks/queries/letters/useGetCakeLetters.ts
  hooks/queries/letters/useGetCakesCount.ts
  hooks/queries/links/useDeleteWishLinks.ts
  hooks/queries/links/useGetOneWish.ts
  hooks/queries/links/useGetWishLinks.ts
  hooks/queries/login/useAuthKakao.ts
  hooks/useDate.ts
  next.config.js
  pages/login/oauth2/code/kakao.tsx
  pages/mypage/letters/[id].tsx
  pages/mypage/letters/[id]/[cakeId].tsx
  pages/mypage/letters/index.tsx
  pages/mypage/links/[id].tsx
  pages/mypage/links/index.tsx
  public/assets/icons/arrowLargeDownIc.svg
  public/assets/icons/arrowLinkIc.svg
  public/assets/icons/deleteBtnIc.svg
  public/assets/icons/index.ts
  public/assets/icons/kakaoLoginIc.svg
  public/assets/images/index.ts
  public/assets/images/linksPageChatImg.svg
  public/assets/images/loginPageChatImg.svg
  public/assets/images/loginPageImg.svg
  public/assets/images/pillCakeImg.svg
  public/assets/images/sharePageCake.svg
  recoil/cakesCountData.ts
  types/letters/cakeLettersType.ts
  types/letters/cakesCountType.ts
  types/links/oneWishType.ts
  types/links/wishLinksType.ts
  types/queryKeyType.ts
Labels: 박재은, Feat, Done

#76 Feat#75 mainPage
  api/main/getProgressData.ts
  components/common/button/buttonBox.tsx
  components/common/mainHeader.tsx
  components/main/button.tsx
  components/main/cake.tsx
  components/main/header.tsx
  components/main/index.tsx
  constant/queryKey.ts
  hooks/queries/main/useGetProgressData.ts
  public/assets/images/index.ts
  public/assets/images/mainEndChatImg.svg
  public/assets/images/mainWishChatImg.svg
  types/queryKeyType.ts
Labels: 박재은, Feat, Done

#71 Feat#69 wishes form
  api/wishes/editUserAccount.ts
  api/wishes/getUserAccount.ts
  components/common/modal/BankInput.tsx
  components/common/uploadTypeToggleBtn.tsx
  components/wishes/wishesForm/BankInfo.tsx
  components/wishes/wishesForm/Preview.tsx
  components/wishes/wishesForm/WisehsStep2.tsx
  components/wishes/wishesForm/WishesStep1.tsx
  components/wishes/wishesForm/index.tsx
  components/wishes/wishesForm/itemImageBox.tsx
  components/wishes/wishesForm/itemLink.tsx
  hooks/common/useInput.tsx
  hooks/queries/wishes/useCreateWishesLink.ts
  hooks/queries/wishes/useGetUserAccount.tsx
  hooks/wishes/useUploadItemInfo.tsx
  pages/wishes/index.tsx
  public/assets/icons/imageUploadIc.svg
  public/assets/icons/index.ts
  types/wishes/accountInfotype.ts
  validation/input.ts
Labels: 홍명헌, Feat, UI, Done

#80 Feat#79 main,mypage
  api/cakes/getWishesData.ts
  api/common/path.ts
  api/letters/getCakeLetters.ts
  api/letters/getCakesCount.ts
  api/links/getOneWish.ts
  api/main/getProgressData.ts
  components/common/dDayText.tsx
  components/common/input/textareaBox.tsx
  components/common/mainHeader.tsx
  components/common/sideContainer.tsx
  components/login/redirect.tsx
  components/main/cake.tsx
  components/main/header.tsx
  components/main/index.tsx
  components/mypage/index.tsx
  components/mypage/itemBox.tsx
  components/mypage/letters/[id].tsx
  components/mypage/letters/cakeListButton.tsx
  components/mypage/letters/cakeListText.tsx
  components/mypage/letters/lettersMain.tsx
  components/mypage/links/[id].tsx
  components/mypage/links/index.tsx
  components/mypage/links/linksBox.tsx
  components/mypage/links/noWishLists.tsx
  components/mypage/links/wishLists.tsx
  components/wishes/share/index.tsx
  constant/siteList.ts
  hooks/mypage/useInitEditWishesInfo.tsx
  hooks/queries/letters/useGetCakeLetters.ts
  hooks/queries/letters/useGetCakesCount.ts
  hooks/queries/links/useGetOneWish.ts
  hooks/queries/login/useAuthKakao.ts
  hooks/queries/main/useGetProgressData.ts
  hooks/queries/wishes/useGetWishesData.ts
  hooks/useKakaoShare.ts
  pages/login/oauth2/code/kakao.tsx
  public/assets/images/GaugeBarImg.svg
  public/assets/images/cakeProfileImg.svg
  public/assets/images/guideContentImg.svg
  public/assets/images/index.ts
  public/assets/images/loginPageImg.svg
  public/assets/images/mainEndCakeImg.svg
  public/assets/images/myPageCakeImg.svg
  public/assets/images/myPageChatImg.svg
  public/assets/images/sharePageCake.svg
  public/assets/images/shop/coupangLogoImg.svg
  recoil/auth/loginUserInfo.ts
  recoil/cakesCountData.ts
  types/auth/loginUserInfo.ts
  types/letters/cakeLettersType.ts
  types/letters/cakesCountType.ts
  types/links/oneWishType.ts
Labels: 박재은, Feat, Done

#83 Refactor#81 cakes
  api/cakes/getWishesData.ts
  api/cakes/requestPayApprove.ts
  api/cakes/requestPayReady.ts
  api/common/path.ts
  components/cakes/SelectCakes.tsx
  components/cakes/approve/successItemBox.tsx
  components/cakes/approve/successMessageBox.tsx
  components/cakes/index.tsx
  components/common/button/button.tsx
  hooks/cakes/useSelectCakes.ts
  hooks/queries/cakes/useGetPgTokenData.ts
  pages/cakes/[id].tsx
  pages/cakes/approve/index.tsx
  recoil/cakes/cakesData.ts
  types/cakes/cakesDataType.ts
Labels: 홍명헌, Fix, Done

#88 Feat-main,letters
  components/common/mainHeader.tsx
  components/common/progressBar.tsx
  components/main/cake.tsx
  components/mypage/letters/[id].tsx
  components/mypage/letters/lettersMain.tsx
  hooks/queries/letters/useGetCakesCount.ts
  recoil/cakesCountData.ts
  types/letters/cakesCountType.ts
Labels: 박재은, Feat, Refactor

#99 [fix] 마이페이지 버튼 비활성화 오류 수정
  components/main/index.tsx
  components/mypage/index.tsx
Labels: 박재은, Fix

#100 Feat QAfeatures
  components/cakes/cakesHeader.tsx
  components/common/button/backBtn.tsx
  components/common/footer.tsx
  components/common/loading.tsx
  components/common/mainView.tsx
  components/common/modal/BankInput.tsx
  components/common/modal/ShareModal.tsx
  components/common/modal/modal.tsx
  components/login/index.tsx
  components/login/redirect.tsx
  components/main/button.tsx
  components/main/index.tsx
  components/mypage/EditWishes/index.tsx
  components/mypage/index.tsx
  components/mypage/letters/[id].tsx
  components/mypage/letters/lettersMain.tsx
  components/mypage/links/[id].tsx
  components/mypage/links/index.tsx
  components/wishes/[id].tsx
  components/wishes/wishesForm/Preview.tsx
  constant/snsList.ts
  package.json
  public/assets/images/index.ts
  public/assets/images/logoNameImg.svg
  yarn.lock
Labels: 박재은, Feat, Done
