Repository Make-A-Wish-Sopt/Make-A-Wish-Client, pull requests merged in 2023-05, with the labels that each got.

#4 Feat#1 common
  .babelrc
  components/common/backBtn.tsx
  components/common/input/inputBox.tsx
  components/common/input/inputLength.tsx
  components/common/inputHeader.tsx
  hooks/useInput.tsx
  package.json
  public/assets/icons/backBtnIc.svg
  public/assets/icons/index.ts
  styles/GlobalStyle.tsx
  styles/theme.ts
  yarn.lock
Labels: 홍명헌, Feat, UI

#7 Feat#5 giver UI
  components/button/backBtn.tsx
  components/button/buttonBox.tsx
  components/common/input/input.tsx
  components/common/input/inputBox.tsx
  components/common/input/inputCakeBox.tsx
  components/common/input/inputContainer.tsx
  components/common/input/inputLength.tsx
  components/common/input/inputTitle.tsx
  components/common/input/textareaBox.tsx
  constant/cakeList.ts
  constant/limitText.ts
  hooks/useInput.tsx
  pages/giver.tsx
  public/assets/icons/backBtn_ic.svg
  public/assets/icons/index.ts
  public/assets/images/beefCakeDetail_img.svg
  public/assets/images/beefCake_img.svg
  public/assets/images/chickenCakeDetail_img.svg
  public/assets/images/chickenCake_img.svg
  public/assets/images/coffeeCakeDetail_img.svg
  public/assets/images/coffeeCake_img.svg
  public/assets/images/flowerCakeDetail_img.svg
  public/assets/images/flowerCake_img.svg
  public/assets/images/index.ts
  public/assets/images/perfumeCakeDetail_img.svg
  public/assets/images/perfumeCake_img.svg
  public/assets/images/poopCakeDetail_img.svg
  public/assets/images/poopCake_img.svg
  public/assets/images/sushiCakeDetail_img.svg
  public/assets/images/sushiCake_img.svg
  public/assets/images/test.jpg
  public/assets/images/vitaminCakeDetail_img.svg
  public/assets/images/vitaminCake_img.svg
  styles/theme.ts
  types/cakeListType.ts
  types/limitTestType.ts
Labels: 홍명헌, UI, Done

#13 Feat#6 giver function
  components/giver/giverHeader.tsx
  pages/giver.tsx
  styles/GlobalStyle.tsx
Labels: 홍명헌, Feat, Done

#17 Feat#15 form page/item crawling
  api/common/axios.ts
  api/common/path.ts
  api/formPage/getItemData.ts
  api/giver/payReady.ts
  components/common/presentImageBox.tsx
  components/formPage/itemLink.tsx
  constant/queryKey.ts
  next.config.js
  package.json
  pages/formPage.tsx
  types/queryKeyType.ts
  validation/input.ts
Labels: 홍명헌, Feat, UI, Done

#18 Feat#16 form page/state
  components/modal/BankModal.tsx
  pages/formPage.tsx
  types/wishesData.ts
  validation/input.ts
Labels: 홍명헌, Feat

#22 Feat#14 giver/api
  api/cakes/getPgTokenData.ts
  api/cakes/getWishesData.ts
  api/cakes/postPayApprove.ts
  api/cakes/postPayReady.ts
  api/common/axios.ts
  api/common/path.ts
  api/giver/payReady.ts
  components/button/buttonBox.tsx
  components/cakes/approve/successItemBox.tsx
  components/cakes/approve/successMsgBox.tsx
  components/cakes/cakesHeader.tsx
  components/cakes/contribution.tsx
  components/common/input/inputLargeBox.tsx
  components/common/progressBar.tsx
  components/giver/giverHeader.tsx
  constant/cakeList.ts
  constant/queryKey.ts
  next.config.js
  package.json
  pages/cakes/[approve].tsx
  pages/cakes/index.tsx
  pages/formPage.tsx
  pages/formPreviewPage.tsx
  public/assets/images/cakes/beefCakeDetailImg.svg
  public/assets/images/cakes/beefCakeImg.svg
  public/assets/images/cakes/beefCakeThanksImg.svg
  public/assets/images/cakes/chickenCakeDetailImg.svg
  public/assets/images/cakes/chickenCakeImg.svg
  public/assets/images/cakes/chickenCakeThanksImg.svg
  public/assets/images/cakes/coffeeCakeDetailImg.svg
  public/assets/images/cakes/coffeeCakeImg.svg
  public/assets/images/cakes/coffeeCakeThanksImg.svg
  public/assets/images/cakes/flowerCakeDetailImg.svg
  public/assets/images/cakes/flowerCakeImg.svg
  public/assets/images/cakes/flowerCakeThanksImg.svg
  public/assets/images/cakes/perfumeCakeDetailImg.svg
  public/assets/images/cakes/perfumeCakeImg.svg
  public/assets/images/cakes/perfumeCakeThanksImg.svg
  public/assets/images/cakes/poopCakeDetailImg.svg
  public/assets/images/cakes/poopCakeImg.svg
  public/assets/images/cakes/poopCakeThanksImg.svg
  public/assets/images/cakes/sushiCakeDetailImg.svg
  public/assets/images/cakes/sushiCakeImg.svg
  public/assets/images/cakes/sushiCakeThanksImg.svg
  public/assets/images/cakes/vitaminCakeDetailImg.svg
  public/assets/images/cakes/vitaminCakeImg.svg
  public/assets/images/cakes/vitaminCakeThanksImg.svg
  public/assets/images/index.ts
  public/assets/testImage.jpeg
  reocil/cakes/cakesData.ts
  types/cakeListType.ts
  types/cakes/cakesDataType.ts
  types/queryKeyType.ts
  util/common/convertMoneyText.ts
  yarn.lock
Labels: 홍명헌, Feat, Done

#23 Feat#16 form page/state
  components/common/backBtn.tsx
  components/formPage/itemLink.tsx
  pages/formPage.tsx
  pages/formPreviewPage.tsx
  recoil/formPage/wishesData.ts
  types/wishesData.ts
Labels: 홍명헌, Feat

#26 Feat#25 common/modal
  components/common/input/inputBankBox.tsx
  components/common/input/inputLargeBox.tsx
  components/common/modal.tsx
  components/modal/BankModal.tsx
  components/modal/termsModal.tsx
  hooks/useModal.tsx
  pages/formPage.tsx
  pages/formPreviewPage.tsx
  public/assets/icons/detailCloseIC.svg
  public/assets/icons/detailOpenIC.svg
  public/assets/icons/index.ts
Labels: 홍명헌, Feat, UI, Done

#31 Feat#29 calendar
  components/common/footer.tsx
  components/modal/DatePickerModal.tsx
  interfaces/ShareData.tsx
  package.json
  pages/formPage.tsx
  pages/formSharePage.tsx
  pages/giverMainPage.tsx
  pages/loginPage.tsx
  pages/mainPage.tsx
  recoil/formPage/wishesData.ts
  yarn.lock
Labels: 박재은, Feat, Done

#35 Feat#24 form page/present info api
  api/common/path.ts
  api/formPage/getItemData.ts
  api/formPreviewPage/createWishesLink.ts
  components/formPage/itemLink.tsx
  constant/parsingTagKey.ts
  interfaces/SiteData.tsx
  next.config.js
  pages/formPage.tsx
  pages/formPreviewPage.tsx
  recoil/formPage/wishesData.ts
  types/formPage/parsingTagKeyType.ts
  types/wishesDataType.ts
Labels: 홍명헌, Done
